version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-test-renderer"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native-web"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native-webview"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native-svg"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-router"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "babel-preset-expo"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@sentry/react-native"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    groups:
      jest-and-testing:
        patterns:
          - "jest"
          - "jest-*"
          - "babel-jest"
          - "jest-expo"
          - "@types/jest"
          - "@testing-library/*"
        update-types: ["minor", "patch"]
      eslint-and-linting:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
          - "eslint-config-*"
          - "eslint-plugin-*"
        update-types: ["minor", "patch"]
      typescript-and-types:
        patterns:
          - "typescript"
          - "tslib"
          - "@types/*"
        update-types: ["minor", "patch"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
