version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

    # Ignore Expo-managed deps so they stay aligned with SDK 53.
    # (Revisit when you explicitly upgrade the SDK.)
    ignore:
      # Core React/RN we don't want auto-bumped
      - dependency-name: "react"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-test-renderer"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]

      # Expo SDK & preset
      - dependency-name: "expo"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "babel-preset-expo"   # keep within SDK preset
        update-types: ["version-update:semver-minor", "version-update:semver-major"]

      # Expo libraries (explicit list from your package.json)
      - dependency-name: "expo-blur"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-constants"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-font"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-haptics"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-image"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-linking"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-router"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-splash-screen"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-status-bar"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-symbols"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-system-ui"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "expo-web-browser"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]

      # RN ecosystem packages Expo pins
      - dependency-name: "react-native-web"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native-webview"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native-gesture-handler"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native-reanimated"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native-screens"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native-safe-area-context"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]
      - dependency-name: "react-native-svg"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]

      # Other majors you already wanted to hold
      - dependency-name: "@sentry/react-native"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

      # Optional: vector icons are tied to Expo templates; avoid auto drift
      - dependency-name: "@expo/vector-icons"
        update-types: ["version-update:semver-minor", "version-update:semver-major"]

    groups:
      jest-and-testing:
        patterns:
          - "jest"
          - "jest-*"
          - "babel-jest"
          - "jest-expo"
          - "@types/jest"
          - "@testing-library/*"
        update-types: ["minor", "patch"]
      eslint-and-linting:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-*"
          - "eslint-config-*"
          - "eslint-plugin-*"
        update-types: ["minor", "patch"]
      typescript-and-types:
        patterns:
          - "typescript"
          - "tslib"
          - "@types/*"
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
