name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
      placeholder: It crashed when I tapped...
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: App version
      placeholder: e.g. 1.0.0 (build 12)
  - type: input
    id: device
    attributes:
      label: Device & OS
      placeholder: e.g. iPhone 14 / iOS 17.5, Pixel 7 / Android 14
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
  - type: textarea
    id: logs
    attributes:
      label: Any logs or screenshots?

